version: '3'
services:
  app:
    image: node:18
    working_dir: /app
    volumes:
    - .:/app
    tty: true
    ports:
      - "80:8080"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb